# Generated by Django 3.1.3 on 2023-02-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_properties'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
    ]
